# -*- coding: utf-8 -*-
"""calculadora.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZ9kaZTT9A6OUWP7Poc_VObDHwEaLrSy
"""

num1=float(input("Digite a medida da base: "))
num2=float(input("Digite a medida da altura: "))
multiplicação= num1*num2
print("Resultado da área: ", multiplicação)